/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminFollowUpRouteImport } from './routes/admin.follow-up'
import { Route as AdminLeaveRouteImport } from './routes/admin.leave'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorConsultationsRouteImport } from './routes/doctor.consultations'
import { Route as DoctorLeaveRouteImport } from './routes/doctor.leave'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientTriageRouteImport } from './routes/patient.triage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowUpRoute = AdminFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaveRoute = AdminLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorConsultationsRoute = DoctorConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorLeaveRoute = DoctorLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTriageRoute = PatientTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/triage': typeof PatientTriageRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/triage': typeof PatientTriageRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/consultations': typeof DoctorConsultationsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/triage': typeof PatientTriageRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/register'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/follow-up'
    | '/admin/leave'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/leave'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/history'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/triage'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/follow-up'
    | '/admin/leave'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/leave'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/history'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/triage'
    | '/admin'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/register'
    | '/admin/appointments'
    | '/admin/billing'
    | '/admin/departments'
    | '/admin/follow-up'
    | '/admin/leave'
    | '/admin/users'
    | '/doctor/consultations'
    | '/doctor/leave'
    | '/doctor/profile'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/history'
    | '/patient/notifications'
    | '/patient/profile'
    | '/patient/triage'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/follow-up': {
      id: '/admin/follow-up'
      path: '/follow-up'
      fullPath: '/admin/follow-up'
      preLoaderRoute: typeof AdminFollowUpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leave': {
      id: '/admin/leave'
      path: '/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AdminLeaveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/consultations': {
      id: '/doctor/consultations'
      path: '/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof DoctorConsultationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/leave': {
      id: '/doctor/leave'
      path: '/leave'
      fullPath: '/doctor/leave'
      preLoaderRoute: typeof DoctorLeaveRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/triage': {
      id: '/patient/triage'
      path: '/triage'
      fullPath: '/patient/triage'
      preLoaderRoute: typeof PatientTriageRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFollowUpRoute: typeof AdminFollowUpRoute
  AdminLeaveRoute: typeof AdminLeaveRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFollowUpRoute: AdminFollowUpRoute,
  AdminLeaveRoute: AdminLeaveRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorConsultationsRoute: typeof DoctorConsultationsRoute
  DoctorLeaveRoute: typeof DoctorLeaveRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorConsultationsRoute: DoctorConsultationsRoute,
  DoctorLeaveRoute: DoctorLeaveRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientTriageRoute: typeof PatientTriageRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientTriageRoute: PatientTriageRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
